name: main

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1 
      - name: Open PR for new release of Krew Plugin
        uses: rajatjindal/krew-plugin-release@v0.0.14
        with:
          plugin-name: 'modify-secret'
          upstream-krew-index-owner: 'rajatjin'
        env:
          KREW_PLUGIN_RELEASE_TOKEN: ${{ secrets.KREW_PLUGIN_RELEASE_TOKEN }}



